FORMAT: 1A
# FruitPal API Doc

# GET /prices

+ Request
    + Parameters
        + commodity(string, optional,`pineapple`) - This is the id for commodities
        + price_per_trade(float,optional,`100`) - This is the id price per trade
        + volume_in_tons(number, optional, `1`) - This is the id for volume in tons

+ Response 200 (application/json)
    + Body

        {'PRICES':[{'COST': '102.58' ,'COUNTRY':'BR'}]}

+ Request
    + Parameters
        + commodity(string, optional,`mango`) - This is the id for commodities
        + price_per_trade(float,optional,`100`) - This is the id price per trade
        + volume_in_tons(number, optional, `1`) - This is the id for volume in tons

+ Response 200 (application/json)

    + Body

        {'PRICES':[{'COST': '153.00' ,'COUNTRY':'MX'}, {'COST': '152.85' ,'COUNTRY':'BR'}]}


# GET  /commodities

+ Response 200 (application/json)
    + Body

        { "COMMODITIES": ["mango", "pineapple", "apple"] }